### ISSUE TITLE
Put commands on github

### ISSUE THREAD

**Issue by moul** [ultreme/m1ch3l#1]
- [x] create an `ultreme-bot` github account
- [x] commit + push existing commands
- [x] add a commit + push hook when we add new commands
- [x] add a cron that pull github commands to allow editing

**Comment by moul** [comment]
Do not forget to setup git for m1ch3l with ultreme-bot user

**Comment by aimxhaisse** [comment]
Yes, I'll add a public key and a cool gitconfig
